import * as functions from "firebase-functions";
import express from "express";
import cors from "cors";
import userRouter from "./routes/userRouter";
import sessionRouter from "./routes/sessionRouter";
const app = express();
app.use(cors());
app.use(express.json());
app.use("/leaderboard", userRouter);
app.use("/session", sessionRouter);
export const api = functions.https.onRequest(app);
